import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Tabs, TabList, TabPanels, Tab, TabPanel, Text, Button, Stack, SimpleGrid  } from '@chakra-ui/react'

export default function Home() {
  return (
    <div style={{ backgroundImage: "url(/light_red.jpg)" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Your Newest Crypto</a>
        </h1>

        <p className={styles.description}>
          <SimpleGrid columns = {2} spacing = {10}>
            <Image src="/coins.jpg" alt = "crypto pic" width = {300} height = {200}></Image>
            <Image src="/cornell.jpeg" alt = "crypto pic" width = {300} height = {200}></Image>
          </SimpleGrid>
        </p>
        <Button colorScheme='teal' size='lg'>
          CUBucks
        </Button>
        <br></br>
        <Tabs>
          <TabList>
            <Tab>
              <Text fontSize='30px' color='black'>
               Effective
              </Text>
            </Tab>
            <Tab>
              <Text fontSize='30px' color='black'>
                Fast
              </Text>
            </Tab>
            <Tab>
            <Text fontSize='30px' color='black'>
               Safe
              </Text>
            </Tab>
          </TabList>

          <TabPanels>
            <TabPanel>
              <p>Full replacement for BRBs! Come to Cornell, buy anything.</p>
            </TabPanel>
            <TabPanel>
              <p>Leverage smart contracts effectively for rapid exchanges.</p>
            </TabPanel>
            <TabPanel>
              <p>Verify with Cornell ID. Safe and secure</p>
            </TabPanel>
          </TabPanels>
        </Tabs>
        <br></br>
        <br></br>
        <Text fontSize='35px' color='black'>
          Changing the industry. For good
        </Text>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
              <Text fontSize='20px' color='black'>
                Powered by
              </Text>
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
